### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [asingh1969/tc359-project11#1]
Looks mostly very good. I just see one thing I'd like you to update:
- When I'm not signed in and on the Show page, I still see a link to Edit, which should probably be hidden since I can't _really_ edit anything.

**Comment by asingh1969** [comment]
should be fixed now sorry it took so long.

**Comment by chrisvfritz** [comment]
I just have [one small refactor](https://github.com/asingh1969/tc359-project11/commit/5a7684bf44839217291933d01bb30c62d1fa619b#diff-853dfcfe6b536f1b319c30fae14aa28dR23#diff-0) I'd like you to make to shorten things.

**Comment by asingh1969** [comment]
Of course you only put a conditional around only something that is conditional, how did I miss that. Thanks for the catch!

**Comment by chrisvfritz** [comment]
:+1: Looks good! I miss little stuff too sometimes. That's why code reviews are useful. :smiley:
